name: Publish Package to npmjs

on:
  pull_request:
    branches: [master]

# 使用正式版本测一下
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          cache: 'yarn'
      - name: 设置git config 信息
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm release ${{ secrets.NPM_TOKEN }} ${{secrets.ACTION_TOKEN}} ${{github.event.pull_request.base.ref}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
